### ISSUE TITLE
Pre release to-do list

### ISSUE THREAD

**Issue by jamieoneill** [jamieoneill/countdown#1]
#### Tasks checklist
- [x] Enable game types (classic & knockout)
- [x] Add game configs (number of rounds, timer duration, etc)
- [x] Add conundrum round
- [x] Update dictionary
- [x] Determine best possible word for letter game
- [x] Update input number detection
- [x] Add information (rules, game modes, link to git, legal)
- [x] ~Deploy to Firebase hosting (testing express on Firebase)~ Not supported
- [x] Deploy to Heroku
- [x] ~Change server to HTTPS~ Heroku is HTTPS by default
- [ ] Stress testing (number of users in a room, number of rooms at once)
- [x] Update app icon & splash screen
- [ ] Offline mode (vs cpu or a solo game)
- [x] Mobile UI fixes (create room does not tab, information not hidden, PWA name not correct, notification badge not in correct position, back button position slightly off, viewport is not actual screen size, hide all elements in css and enable with js for better loading exp)
- [x] Invite to room system
- [x] Redirect user if trying to join a started game
- [x] Apply full countdown rules (number of vowels that can be selected, variance in small/large numbers)
- [x] Allow user to leave room and join another

**Comment by jamieoneill** [comment]
Conundrum round added

**Comment by jamieoneill** [comment]
Not going to do stress testing as i don't have that many users to do it with. documentation for socket states 10,000 users can connect without performance drop.

Not adding an offline mode for now (or ever...?). Seems out of scope for a targeted multiplayer game
